In [3]:
import pandas as pd

In [4]:
import pandas as pd

delta_data = pd.DataFrame([
    {
        "company": "Delta Corporation Limited",
        "report_year": 2026,
        "metric": "Revenue",
        "value": 1_091_805,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
    {
        "company": "Delta Corporation Limited",
        "report_year": 2025,
        "metric": "Revenue",
        "value": 807_470,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
])

delta_data

additional_metrics = pd.DataFrame([
    {
        "company": "Delta Corporation Limited",
        "report_year": 2026,
        "metric": "Net operating income",
        "value": 208_687,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
    {
        "company": "Delta Corporation Limited",
        "report_year": 2025,
        "metric": "Net operating income",
        "value": 147_086,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
    {
        "company": "Delta Corporation Limited",
        "report_year": 2026,
        "metric": "Total assets",
        "value": 591_435,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
    {
        "company": "Delta Corporation Limited",
        "report_year": 2025,
        "metric": "Total assets",
        "value": 442_388,
        "unit": "US$'000",
        "source": "Delta Corporation Limited Annual Report 2026",
    },
])

delta_data = pd.concat([delta_data, additional_metrics], ignore_index=True)

delta_data

,company,report_year,metric,value,unit,source
0,Delta Corporation Limited,2026,Revenue,1091805,US$'000,Delta Corporation Limited Annual Report 2026
1,Delta Corporation Limited,2025,Revenue,807470,US$'000,Delta Corporation Limited Annual Report 2026
2,Delta Corporation Limited,2026,Net operating income,208687,US$'000,Delta Corporation Limited Annual Report 2026
3,Delta Corporation Limited,2025,Net operating income,147086,US$'000,Delta Corporation Limited Annual Report 2026
4,Delta Corporation Limited,2026,Total assets,591435,US$'000,Delta Corporation Limited Annual Report 2026
5,Delta Corporation Limited,2025,Total assets,442388,US$'000,Delta Corporation Limited Annual Report 2026

In [5]:
print('Missing values per column:')
print(delta_data.isnull().sum())

print('\nDuplicate records:')
print(delta_data.duplicated().sum())

print('\nData types:')
print(delta_data.dtypes)

Missing values per column:
company        0
report_year    0
metric         0
value          0
unit           0
source         0
dtype: int64

Duplicate records:
0

Data types:
company          str
report_year    int64
metric           str
value          int64
unit             str
source           str
dtype: object

In [6]:
#year on year revenue growth
revenue_2025 = delta_data.loc[
    (delta_data['metric'] == 'Revenue') & (delta_data['report_year'] == 2025),
    'value'
].iloc[0]

revenue_2026 = delta_data.loc[
    (delta_data['metric'] == 'Revenue') & (delta_data['report_year'] == 2026), 'value'
].iloc[0]

revenue_growth = (
(revenue_2026 - revenue_2025) / revenue_2025
)*100

print(f'Revenue growth: {revenue_growth:.2f}%')

Revenue growth: 35.21%

In [7]:
#net operating income growth
income_2025 = delta_data.loc[
    (delta_data['metric'] == 'Net operating income') & (delta_data['report_year'] == 2025),
    'value'
].iloc[0]

income_2026 = delta_data.loc[
    (delta_data['metric'] == 'Net operating income') & (delta_data['report_year'] == 2026),
    'value'
].iloc[0]

income_growth = (
    (income_2026 - income_2025) / income_2025
) * 100

print(f"Net operating income growth: {income_growth:.2f}%")

Net operating income growth: 41.88%

In [8]:
#operating margin
margin_2025 = (income_2025 / revenue_2025) * 100
margin_2026 = (income_2026 / revenue_2026) * 100

print(f"2025 operating margin: {margin_2025:.2f}%")
print(f"2026 operating margin: {margin_2026:.2f}%")
print(f"Change in margin: {margin_2026 - margin_2025:.2f} percentage points")

2025 operating margin: 18.22%
2026 operating margin: 19.11%
Change in margin: 0.90 percentage points

In [9]:
#asset growth rate
assets_2025 = delta_data.loc[
    (delta_data['metric'] == 'Total assets') & (delta_data['report_year'] == 2025),
    'value'
].iloc[0]

assets_2026 = delta_data.loc[
    (delta_data['metric'] == 'Total assets') & (delta_data['report_year'] == 2026), 'value'
].iloc[0]

asset_growth = ((assets_2026 - assets_2025) / assets_2025)*100

print(f'2025 total assets: US${assets_2025:,} thousand')
print(f'2026 total assets: US${assets_2026:,} thousand')
print(f'Total asset growth: {asset_growth:.2f}%')

2025 total assets: US$442,388 thousand
2026 total assets: US$591,435 thousand
Total asset growth: 33.69%

In [12]:
#return on assets(ROA): helps us assess how much net operating income the company generated relative to its assets.

print(income_2025, assets_2025, income_2026, assets_2026)

roa_2025 = (income_2025 / assets_2025) * 100
roa_2026 = (income_2026 / assets_2026) * 100
print(f'2025 return on assets: {roa_2025:.2f}%')
print(f'2026 return on assets: {roa_2026:.2f}%')
print(f'Change in ROA: {roa_2026 - roa_2025:.2f} percentage points')

147086 442388 208687 591435
2025 return on assets: 33.25%
2026 return on assets: 35.28%
Change in ROA: 2.04 percentage points

In [14]:
kpi_summary = pd.DataFrame({
    'Metric': ['Revenue growth',
               'Net operating income growth',
               'Operating margin (2025)',
               'Operating margin (2026)',
               'Total asset growth',
               'Operating income / year-end assets (2025)',
               'Operating income / year-end assets (2026)',],
    'Value': [
        revenue_growth,
        income_growth,
        margin_2025,
        margin_2026,
        asset_growth,
        roa_2025,
        roa_2026,
    ],
    'Unit': [
        '%',
        '%',
        '%',
        '%',
        '%',
        '%',
        '%',
    ],
})

kpi_summary.round(2)

                                      Metric  Value Unit
0                             Revenue growth  35.21    %
1                Net operating income growth  41.88    %
2                    Operating margin (2025)  18.22    %
3                    Operating margin (2026)  19.11    %
4                         Total asset growth  33.69    %
5  Operating income / year-end assets (2025)  33.25    %
6  Operating income / year-end assets (2026)  35.28    %

In [16]:
from pathlib import Path

output_path = Path('../data/processed/delta_financial_data.csv')
output_path.parent.mkdir(parents=True, exist_ok=True)

delta_data.to_csv(output_path, index=False)
print(f'Saved to: {output_path.resolve()}')

Saved to: C:\Users\alist\Desktop\zim_company_analytics\data\processed\delta_financial_data.csv

In [17]:
#verify the saved csv
saved_data = pd.read_csv(output_path)
print('Rows:', len(saved_data))
print('Columns:', list(saved_data.columns))

saved_data.head()

Rows: 6
Columns: ['company', 'report_year', 'metric', 'value', 'unit', 'source']

,company,report_year,metric,value,unit,source
0,Delta Corporation Limited,2026,Revenue,1091805,US$'000,Delta Corporation Limited Annual Report 2026
1,Delta Corporation Limited,2025,Revenue,807470,US$'000,Delta Corporation Limited Annual Report 2026
2,Delta Corporation Limited,2026,Net operating income,208687,US$'000,Delta Corporation Limited Annual Report 2026
3,Delta Corporation Limited,2025,Net operating income,147086,US$'000,Delta Corporation Limited Annual Report 2026
4,Delta Corporation Limited,2026,Total assets,591435,US$'000,Delta Corporation Limited Annual Report 2026